FIRST_YEAR_MVP = 1956
FIRST_YEAR_NBA = 1950
CURRENT_YEAR = 2025
PREVIOUS_YEAR = CURRENT_YEAR - 1

TEAM_MAPPING = {
    "ATL": "Atlanta Hawks",
    "BOS": "Boston Celtics",
    "BRK": "Brooklyn Nets",
    "CHO": "Charlotte Hornets",
    "CHH": "Charlotte Hornets",
    "CHI": "Chicago Bulls",
    "CLE": "Cleveland Cavaliers",
    "DAL": "Dallas Mavericks",
    "DEN": "Denver Nuggets",
    "DET": "Detroit Pistons",
    "GSW": "Golden State Warriors",
    "HOU": "Houston Rockets",
    "IND": "Indiana Pacers",
    "LAC": "Los Angeles Clippers",
    "LAL": "Los Angeles Lakers",
    "MEM": "Memphis Grizzlies",
    "MIA": "Miami Heat",
    "MIL": "Milwaukee Bucks",
    "MIN": "Minnesota Timberwolves",
    "NOP": "New Orleans Pelicans",
    "NYK": "New York Knicks",
    "OKC": "Oklahoma City Thunder",
    "ORL": "Orlando Magic",
    "PHI": "Philadelphia 76ers",
    "PHO": "Phoenix Suns",
    "POR": "Portland Trail Blazers",
    "SAC": "Sacramento Kings",
    "SAS": "San Antonio Spurs",
    "TOR": "Toronto Raptors",
    "UTA": "Utah Jazz",
    "WAS": "Washington Wizards",

    # Defunct or Relocated Teams
    "VAN": "Vancouver Grizzlies",
    "SEA": "Seattle SuperSonics",
    "NJN": "New Jersey Nets",
    "NYN": "New York Nets",
    "NOH": "New Orleans Hornets",
    "NOK": "New Orleans/Oklahoma City Hornets",
    "NOJ": "New Orleans Jazz",
    "SDC": "San Diego Clippers",
    "BUF": "Buffalo Braves",
    "KCK": "Kansas City Kings",
    "CIN": "Cincinnati Royals",
    "ROC": "Rochester Royals",
    "PHW": "Philadelphia Warriors",
    "SFW": "San Francisco Warriors",
    "FTW": "Fort Wayne Pistons",
    "STL": "St. Louis Hawks",
    "MLH": "Milwaukee Hawks",
    "TCB": "Tri-Cities Blackhawks",
    "SYR": "Syracuse Nationals",
    "BAL": "Baltimore Bullets",
    "WSB": "Washington Bullets",
    "CHS": "Chicago Stags",
    "AND": "Anderson Packers",
    "SHE": "Sheboygan Red Skins",
    "WAT": "Waterloo Hawks",
    "PRO": "Providence Steamrollers",
    "MNL": "Minneapolis Lakers",
    "CHA": "Charlotte Bobcats",
    "SDR": "San Diego Rockets",
    "KCO": "Kansas City-Omaha Kings",
    "CAP": "Capital Bullets",
    "CHP": "Chicago Packers",
    "CHZ": "Chicago Zephyrs",
    "2TM": "2TM",
    "3TM": "3TM",
    "4TM": "4TM",
    "5TM": "5TM"
}